---
- name: Install operators 
  kubernetes.core.helm:
    name: service-mesh-operators
    chart_ref: "../charts/install_sm_operators_with_helm/service-mesh-operators"
    release_namespace: openshift-operators
    values:
      approval_strategy: "{{ approval_strategy }}"
- name: Wait Until Elasticsearch Subscription Is Deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "elasticsearch-operator"
    namespace: openshift-operators 
  register: r_subscription_elasticsearch
  retries: 25
  delay: 5
  until:
     - r_subscription_elasticsearch.resources[0].status.currentCSV is defined
     - r_subscription_elasticsearch.resources[0].status.currentCSV | length > 0
- name: Wait Until Jaeger Subscription Is Deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: jaeger-product
    namespace: openshift-operators 
  register: r_subscription_jaeger
  retries: 25
  delay: 2
  until:
     - r_subscription_jaeger.resources[0].status.currentCSV is defined
     - r_subscription_jaeger.resources[0].status.currentCSV | length > 0
- name: Wait Until Kiali Subscription Is Deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: kiali-ossm
    namespace: openshift-operators 
  register: r_subscription_kiali_ossm
  retries: 25
  delay: 2
  until:
     - r_subscription_kiali_ossm.resources[0].status.currentCSV is defined
     - r_subscription_kiali_ossm.resources[0].status.currentCSV | length > 0
- name: Wait Until Service Mesh Subscription Is Deployed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: servicemeshoperator
    namespace: openshift-operators 
  register: r_subscription_servicemeshoperator
  retries: 25
  delay: 2
  until:
     - r_subscription_servicemeshoperator.resources[0].status.currentCSV is defined
     - r_subscription_servicemeshoperator.resources[0].status.currentCSV | length > 0
