apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.control_plane_name }}
spec:
  version: v2.0
{{- if .Values.enable_mtls_security }}
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
{{- end }}
  tracing:
{{- if .Values.disable_tracing }}
    type: None
{{- else }}
    sampling: 10000 
    type: Jaeger
{{- end }}
  profiles:
    - default
  proxy:
    injection:
      autoInject: {{ .Values.proxy_autoinjection }}
    runtime:
      container:
        resources:
          requests:
            cpu: {{ .Values.smcp_proxy_runtime_cpu_requests }}
            memory: {{ .Values.smcp_proxy_runtime_memory_requests }}
  gateways:
    egress:
{{- if .Values.smcp_enable_custom_egress_config }}
{{ .Files.Get .Values.smcp_custom_egress_config_file | indent 6 }}
{{- else }}
      enabled: false
      service: {}
{{- end }}
    ingress:
{{- if .Values.smcp_enable_custom_ingress_config }}
{{ .Files.Get .Values.smcp_custom_ingress_config_file | indent 6 }}
{{- else }}
      enabled: true
      service: {}
{{- end }}
  addons:
    grafana:
      enabled: {{ .Values.enable_grafana }}
    jaeger:
{{- if .Values.is_production_deployment }}
      name: jaeger-production
      install:
        storage:
          type: Elasticsearch
{{- else }}
      name: jaeger
      install:
        storage:
          type: Memory
{{- end }}
        ingress:
          enabled: true
    kiali:
      enabled: {{ .Values.enable_kiali }}
    prometheus:
      enabled: {{ .Values.enable_prometheus }}
{{- if or .Values.enable_kiali .Values.enable_grafana .Values.enable_prometheus }}
  runtime:
    components:
      grafana:
        container:
          resources:
            requests:
              cpu: {{ .Values.smcp_runtime_grafana_cpu_requests }}
              memory: {{ .Values.smcp_runtime_grafana_memory_requests }}
      kiali:
        container:
          resources:
            requests:
              cpu: {{ .Values.smcp_runtime_kiali_cpu_requests }}
              memory: {{ .Values.smcp_runtime_kiali_memory_requests }}
      tracing.jaeger:
        container:
          resources:
            requests:
              cpu: {{ .Values.smcp_runtime_tracing_jaeger_cpu_requests }}
              memory: {{ .Values.smcp_runtime_tracing_jaeger_memory_requests }}o{{- end }}
