apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.control_plane_name }}
spec:
  version: v2.0
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
  tracing:
    sampling: 10000 
    type: Jaeger
  profiles:
    - default
  proxy:
    runtime:
      container:
        resources:
          requests:
            cpu: {{ .Values.smcp_proxy_runtime_cpu_requests }}
            memory: {{ .Values.smcp_proxy_runtime_memory_requests }}
  gateways:
    additionalIngress:
      {{ .Values.ingressgateway_name }}:
        enabled: true
        runtime:
          container:
            resources:
              requests:
                cpu: {{ .Values.smcp_gateway_additional_ingress_runtime_cpu_requests }}
                memory: {{ .Values.smcp_gateway_additional_ingress_runtime_memory_requests }}
          deployment:
            autoScaling:
              enabled: true
        service:
          metadata:
            labels:
              app: {{ .Values.ingressgateway_name }}
              istio: ingressgateway
          ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443
          type: ClusterIP
    egress:
{{- if .Values.smcp_enable_custom_egress_config }}
{{ .Files.Get (.Values.smcp_custom_egress_config_file) | indent 6 }}
{{- else }}
      enabled: false
      service: {}
{{- end }}
    ingress:
{{- if .Values.smcp_enable_custom_ingress_config }}
{{ .Files.Get (.Values.smcp_custom_ingress_config_file) | indent 6 }}
{{- else }}
      enabled: false
      service: {}
{{- end }}
  addons:
    grafana:
      enabled: true
    jaeger:
{{- if .Values.is_production_deployment }}
      name: jaeger-production
      install:
        storage:
          type: Elasticsearch
{{- else }}
      name: jaeger
      install:
        storage:
          type: Memory
{{- end }}
        ingress:
          enabled: true
    kiali:
      enabled: true
  runtime:
    components:
      grafana:
        container:
          resources:
            requests:
              cpu: {{ .Values.smcp_runtime_grafana_cpu_requests }}
              memory: {{ .Values.smcp_runtime_grafana_memory_requests }}
      kiali:
        container:
          resources:
            requests:
              cpu: {{ .Values.smcp_runtime_kiali_cpu_requests }}
              memory: {{ .Values.smcp_runtime_kiali_memory_requests }}
      tracing.jaeger:
        container:
          resources:
            requests:
              cpu: {{ .Values.smcp_runtime_tracing_jaeger_cpu_requests }}
              memory: {{ .Values.smcp_runtime_tracing_jaeger_memory_requests }}
